version: "3"
services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  offer:
    image: 'offer/transfer:1.0'
    deploy:
      replicas: 3
    ports:
      - '8080-8082:8080'
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - DB_HOST=offer-postgres
      - DB_PORT=5432
      - DB_NAME=offer
      - DB_USER=offer
      - DB_PASSWORD=offer
      - PAGING-STATE-TOPIC=paging
      - STATUS-TOPIC=status
      - DLQ-TOPIC=data_dlq
      - DATA-TOPIC=data
      - PARTITION_LAST_INDEX=2
      - PAGE_SIZE=10000
    depends_on:
      - kafka

  offer-postgres:
    build: ./pg-init-scripts
    ports:
      - "5432:5432"



