FROM postgres:15.1

ENV POSTGRES_DB: offer
ENV POSTGRES_USER=offer
ENV POSTGRES_PASSWORD=offer
ENV POSTGRES_MULTIPLE_DATABASES=offer


COPY docker-entrypoint-initdb.sh /docker-entrypoint-initdb.d/docker-entrypoint-initdb.sh